mqtt:
  host: mosquitto_local

detectors:
  openvino:
    type: openvino
    device: AUTO

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  fridge_zone:
    ffmpeg:
      inputs:
        - path: '{FRIGATE_RTSP_PATH}'
          roles:
            - detect
            - record
    detect:
      enabled: false
      width: 1920
      height: 1080
      fps: 5 # Lower FPS to 5; Frigate's official recommendation to avoid overload.
    objects:
      track:
        - bottle
        - cup
        - chair
        - couch
        - potted plant
        - dining table

version: 0.17-0
